import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          layout: {
            logoImageUrl: '/icons/yoom-logo.svg', 
            socialButtonsVariant: 'iconButton'},
          variables: {
            colorPrimary: "#2563eb",
            colorText: "#f3f4f6",
            colorBackground: "#18181b",
            colorInputBackground: "#27272a",
            colorInputText: "#f3f4f6"
            }
          }}>
          <body className={`${inter.className} bg-zinc-900`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
